//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContextContainer : DbContext
    {
        public DataContextContainer()
            : base("name=DataContextContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppointmentBooking> AppointmentBooking { get; set; }
        public virtual DbSet<Availabilityslots> Availabilityslots { get; set; }
        public virtual DbSet<CodeController> CodeController { get; set; }
        public virtual DbSet<DoctorAvailabilityMaster> DoctorAvailabilityMaster { get; set; }
        public virtual DbSet<DoctorSchedule> DoctorSchedule { get; set; }
        public virtual DbSet<Doctorscheduledetails> Doctorscheduledetails { get; set; }
        public virtual DbSet<EmployeeDetails> EmployeeDetails { get; set; }
        public virtual DbSet<LoginCredentials> LoginCredentials { get; set; }
        public virtual DbSet<PatientDetails> PatientDetails { get; set; }
        public virtual DbSet<slotdetails> slotdetails { get; set; }
    }
}
