//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctorscheduledetails
    {
        public int scheduleID { get; set; }
        public Nullable<int> AvailID { get; set; }
        public string session { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual DoctorAvailabilityMaster DoctorAvailabilityMaster { get; set; }
    }
}
