//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginCredential
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
        public virtual PatientDetail PatientDetail { get; set; }
    }
}
