//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class slotdetails
    {
        public int slotID { get; set; }
        public Nullable<int> AvailID { get; set; }
        public string slotTime { get; set; }
        public string status { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string description { get; set; }
        public string canceldescription { get; set; }
        public Nullable<int> scheduleID { get; set; }
    }
}
